/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-10-11 06:26:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class destinoFormulario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Confirmacion de cita</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/estilo2.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String nombres[] = {"Teo","Mercedes","Maite","Teresa","Pedro"};
	String dias[] = {"Lunes","Martes","Miercoles","Jueves","Viernes"};
	String horas[] = {"9:00","10:00","11:00","12:00"};	

	String nombre = request.getParameter("nombreS");
	String dia = request.getParameter("diaS");
	String hora = request.getParameter("hora");
	String obs = request.getParameter("obs");
	String enviar = request.getParameter("enviar");
	if(enviar!=null){
      out.write("\r\n");
      out.write("\t\t<h2>Su cita será: </h2>\r\n");
      out.write("\t\t<table border=\"2\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>Nombre Docente:</th>\r\n");
      out.write("\t\t\t\t<th>Dia:</th>\r\n");
      out.write("\t\t\t\t<th>Hora:</th>\r\n");
      out.write("\t\t\t\t<th>Observaciones:</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(nombres[Integer.parseInt(nombre)]);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(dias[2]);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(horas[1]);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(obs);
      out.write("</td>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t<p><a href=\"FormularioTutoria.jsp\">Ir al formulario otra vez</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
