/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-10-28 21:35:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class seleccionaFormaColorV0_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String forma[] = {"cuadrado","circulo","elipse"};
	String color[] = {"red","blue","purple","yellow","pink"};
	
	ArrayList<String[]> lista = new ArrayList<String[]>();
	
	int posicionX = 0;
	Random rd = new Random();
	
	//if(aleColor == color.length) aleColor=0;
	
	int aleBuscadoColor, aleBuscadoForma, ale;
	aleBuscadoColor = rd.nextInt(color.length);				
	aleBuscadoForma = rd.nextInt(forma.length);
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"destinoSeleccionaFormaColor.jsp\" method=\"post\">\r\n");
      out.write("\t\t");

		for(String v1 : forma){
			for(String v2 : color){
				lista.add(new String[]{v1,v2});
			}
		}
		
		ale = rd.nextInt(lista.size());	
		 
		for (int i=0; i<lista.size(); i++) {
		    int randomPosition = rd.nextInt(lista.size());
		    String temp1 = lista.get(i)[0];
		    String temp2 = lista.get(i)[1];
		    lista.get(i)[0] = lista.get(randomPosition)[0];
		    lista.get(i)[1] = lista.get(randomPosition)[1];
		    lista.get(randomPosition)[0] = temp1;
		    lista.get(randomPosition)[1] = temp2;
		}
		
		for(int i=0;i<lista.size();i++){
			
			String dato = lista.get(i)[0]+":"+lista.get(i)[1];
			String formas = lista.get(i)[0];
			if(formas.equals("cuadrado")){
			
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"usuEscoge\" value=\"");
      out.print(dato);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\"  height=\"250px\" width=\"250px\">\r\n");
      out.write("\t\t\t\t\t\t<rect x=\"30px\" y=\"30px\" width=\"200px\" height=\"200px\" stroke=\"black\" stroke-width=2 fill=\"");
      out.print(lista.get(i)[1]);
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t");

						
		}else if(formas.equals("circulo")){ 
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"usuEscoge\" value=\"");
      out.print(dato);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\"  height=\"250px\" width=\"250px\">\r\n");
      out.write("\t\t\t\t\t\t<circle cx=\"130px\" cy=\"130px\" r=\"90\" stroke=\"black\" stroke-width=”1px” fill=\"");
      out.print(lista.get(i)[1]);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t");

		
						
		}else if(formas.equals("elipse")){ 
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"usuEscoge\" value=\"");
      out.print(dato);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\"  height=\"250px\" width=\"250px\">\r\n");
      out.write("\t\t\t\t\t\t<ellipse cx=\"130px\" cy=\"130px\" rx=\"90\" ry=\"50\" stroke-width=”1px” fill=\"");
      out.print(lista.get(i)[1]);
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t");

			}
			//out.println("( " + lista.get(i)[0] + " " + lista.get(i)[1] + " )");
		}
		
		
		
		
      out.write("\r\n");
      out.write("\t\t<h2>Selecciona el de la forma: ");
      out.print(forma[aleBuscadoForma]);
      out.write(" y con color: ");
      out.print(color[aleBuscadoColor]);
      out.write("</h2>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"debiaBuscarForma\" value=\"");
      out.print(forma[aleBuscadoForma]);
      out.write("\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"debiaBuscarColor\" value=\"");
      out.print(color[aleBuscadoColor]);
      out.write("\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
