/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-10-04 08:26:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import DAO.*;

public final class hotelesArrayList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Hoteles</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		Datos d=new Datos();
		ArrayList<hotel> listaHoteles = d.devolverDatos();
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<h1>Reserva De Hotel</h1>\r\n");
      out.write("\t<form action=\"destinoHotelesArraylist.jsp\" method=\"post\">\r\n");
      out.write("\t\t<select name=\"hotel\" required>\r\n");
      out.write("\t\t");

			for(int i=0;i<listaHoteles.size();i++){
				
      out.write("\r\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(i);
      out.write("\" selected>");
      out.print(listaHoteles.get(i).getNombre());
      out.write("</option>\r\n");
      out.write("\t\t\t");
}
		
      out.write("\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<p>Nombre: <input type=\"text\" name=\"nombre\" required /></p>\r\n");
      out.write("\t\t<p>DNI: <input type=\"text\" name=\"DNI\" required/></p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<p>Selecciona el numero de dias</p>\r\n");
      out.write("\t\t<select name=\"dias\" required>\r\n");
      out.write("\t\t\t");

	for (int i=1;i<7;i++){
	
      out.write("\t\r\n");
      out.write("\t\t<option value=\"");
      out.print(i);
      out.write("\" selected>");
      out.print(i);
      out.write("</option>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<select name=\"Regimen\" required>\r\n");
      out.write("\t\t\t<option value=\"A\">Solo Alojamiento</option>\r\n");
      out.write("\t\t\t<option value=\"AD\" Selected >Alojamiento y desayuno</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<p>EXTRAS</p>\r\n");
      out.write("\t\t<p>Parking interior: <input type=\"checkbox\" name=\"parking\" value=\"parking\"/></p>\r\n");
      out.write("\t\t<p>Jacuzzi: <input type=\"checkbox\" name=\"jacuzzi\" value=\"jacuzzi\" /></p>\r\n");
      out.write("\t\t<p>Gimnasio: <input type=\"checkbox\" name=\"gym\" value=\"gym\" /></p>\r\n");
      out.write("\t<input type=\"submit\" name=\"enviar\" value=\"enviar\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
